language: "en-GB"
tone_instructions: "Focus on Clean Architecture principles, Kotlin idioms, and KMP best practices. Be precise and technical."

reviews:
  profile: "assertive"
  request_changes_workflow: true
  fail_commit_status: true

  # Noise reduction
  review_status: false
  high_level_summary: false
  collapse_walkthrough: true
  poem: false

  auto_review:
    base_branches:
      - main

  path_instructions:
    - path: "composeApp/src/commonMain/**"
      instructions: |
        This is platform-agnostic code. Ensure no platform-specific dependencies.
        Follow Clean Architecture - domain layer should be pure business logic.

    - path: "composeApp/src/androidMain/**"
      instructions: |
        Android-specific implementations. Check for proper use of Android APIs,
        lifecycle awareness, and Material Design compliance.

    - path: "composeApp/src/iosMain/**"
      instructions: |
        iOS-specific implementations. Verify compatibility with iOS platform
        conventions and proper integration with Swift/Objective-C interop.

    - path: "composeApp/src/jvmMain/**"
      instructions: |
        Desktop/JVM-specific implementations. Ensure proper desktop UI patterns
        and JVM-specific optimizations.

    - path: "CLAUDE.md"
      instructions: |
        High-level document to steer AI coding agent Claude Code. Must contain
        all essential context without overlapping significantly with other documents.
        Keep succinct (under 100 lines).

    - path: "*.md"
      instructions: |
        Documentation should be clear, accurate, and aligned with current
        implementation. Check for outdated information.

  pre_merge_checks:
    docstrings:
      mode: "off"

    title:
      mode: "error"
      requirements: "Title should be concise, descriptive, free of typos, and ideally under 60 characters."

    description:
      mode: "error"

    issue_assessment:
      mode: "error"

  finishing_touches:
    docstrings:
      enabled: false

    unit_tests:
      enabled: false

  tools:
    github-checks:
      enabled: true
      timeout_ms: 900000

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "IDEA.md"
      - "arch.md"
      - "README.md"
